// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr1vH-29ofkkww5R6OxSdQj-qN07OdwpY',
    appId: '1:212492031087:web:749cf155296556522ee99a',
    messagingSenderId: '212492031087',
    projectId: 'test-flutter-d85fd',
    authDomain: 'test-flutter-d85fd.firebaseapp.com',
    storageBucket: 'test-flutter-d85fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3QSOopjj6cQxaHGEYjQiK4Q5kSlOM_n0',
    appId: '1:212492031087:android:e0fd3e78bdbe97402ee99a',
    messagingSenderId: '212492031087',
    projectId: 'test-flutter-d85fd',
    storageBucket: 'test-flutter-d85fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDowSIixM_Ma44Y2vp3nmFQuZKvdfV5dIc',
    appId: '1:212492031087:ios:3d3f40df2cba912a2ee99a',
    messagingSenderId: '212492031087',
    projectId: 'test-flutter-d85fd',
    storageBucket: 'test-flutter-d85fd.appspot.com',
    iosBundleId: 'com.gonza.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDowSIixM_Ma44Y2vp3nmFQuZKvdfV5dIc',
    appId: '1:212492031087:ios:978c50c9d61f6f512ee99a',
    messagingSenderId: '212492031087',
    projectId: 'test-flutter-d85fd',
    storageBucket: 'test-flutter-d85fd.appspot.com',
    iosBundleId: 'com.gonza.crud.RunnerTests',
  );
}
